// ASSEMBLE (S2): query-order Markdown with provenance + figures + equations. SPEC §3.2 step 5.

export interface FigureContent {
  /** Path relative to the output Markdown file. */
  assetPath: string;
  caption?: string;
  kind?: string;
}

export interface PageContent {
  pageNumber: number;
  text: string;
  figures: FigureContent[];
  equations: { latex: string; display?: boolean }[];
}

export interface SectionContent {
  title: string;
  startPage: number;
  endPage: number;
  reason?: string;
  pages: PageContent[];
}

export interface AssembleMeta {
  query: string;
  pdfPath: string;
  builtAt: string;
}

export function assembleMarkdown(sections: SectionContent[], meta: AssembleMeta): string {
  const out: string[] = [];
  out.push(`# Extract: ${meta.query}`);
  out.push("");
  out.push(
    `> Generated by **doccut** from \`${meta.pdfPath}\` on ${meta.builtAt}. ` +
      `Sections are ordered by relevance to the query; page numbers cite the source PDF.`,
  );
  out.push("");

  for (const sec of sections) {
    out.push(`## ${sec.title} (source pp. ${sec.startPage}–${sec.endPage})`);
    if (sec.reason) out.push(`\n*Why selected: ${sec.reason}*`);
    out.push("");

    for (const page of sec.pages) {
      const body = page.text.trim();
      if (body.length > 0) {
        out.push(body);
        out.push("");
      }

      for (const fig of page.figures) {
        const cap = fig.caption?.trim() || `Figure (p. ${page.pageNumber})`;
        out.push(`![${escapeAlt(cap)}](${fig.assetPath})`);
        out.push("");
        out.push(`*${cap}${fig.kind ? ` — ${fig.kind}` : ""} (source p. ${page.pageNumber})*`);
        out.push("");
      }

      const eqs = page.equations.filter((e) => e.latex.trim().length > 0);
      if (eqs.length > 0) {
        out.push(`<!-- equations transcribed from p. ${page.pageNumber} -->`);
        for (const eq of eqs) {
          const latex = eq.latex.trim();
          out.push(eq.display === false ? `$${latex}$` : `$$\n${latex}\n$$`);
          out.push("");
        }
      }
    }
  }

  return `${out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}

function escapeAlt(s: string): string {
  return s.replace(/[[\]]/g, "").replace(/\n/g, " ");
}
